substitutions:
  project: "esp32-presence-sensor"
  number: "2"
  board: "lolin_s2_mini"
  framework: "arduino"
  pin_led: "GPIO15"
  ld2410_tx_pin: "GPIO18"
  ld2410_rx_pin: "GPIO33"

esphome:
  name: $project-$number
  friendly_name: $project-$number

esp32:
#  board: esp32dev
  board: $board
  framework:
    type: $framework

packages:
  common: !include include/common-config.yaml
  ld2410: !include include/ld2410.yaml


